# Generated by Django 4.0.5 on 2022-07-17 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_funcionario_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='icone',
            field=models.CharField(choices=[('bi bi-person-circle', 'Engrenagem'), ('bi bi-person-circle', 'Gráfico'), ('bi bi-person-circle', 'Usuários'), ('bi bi-person-circle', 'Design'), ('bi bi-person-circle', 'Mobile'), ('bi bi-person-circle', 'Foguete')], max_length=20, verbose_name='Icone'),
        ),
    ]
